### ISSUE TITLE
Cannot call method 'replace' of undefined

### ISSUE THREAD

**Issue by rahilwazir** [strongloop/loopback-example-ssl#4]
The error occurring:

```
/home/a/b/myproject/server/boot/explorer.js:17
    var baseUrl = server.get('url').replace(/\/$/, '');
                                    ^
TypeError: Cannot call method 'replace' of undefined
  at EventEmitter.<anonymous> ( /home/a/b/myproject/server/boot/explorer.js:17:37)
  at EventEmitter.g (events.js:180:16)
  at EventEmitter.emit (events.js:95:17)
  at Server.<anonymous> ( /home/a/b/myproject/server/server.js:122:13)
  at Server.g (events.js:180:16)
  at Server.emit (events.js:92:17)
  at net.js:1056:10
  at process._tickDomainCallback (node.js:492:13)
  at process.<anonymous> ( /home/a/b/myproject/node_modules/loopback/node_modules/continuation-local-storage/node_modules/async-listener/index.js:18:15)
  at Function.Module.runMain (module.js:499:11)
  at startup (node.js:119:16)
  at node.js:935:3
```

I have to use `app.set('url', baseUrl);` before `app.emit()`

```
app.set('url', baseUrl);
app.emit('started', baseUrl);
```

and it worked fine

**Comment by jduhls** [comment]
Thanks for that. Was getting same error.

```
strongloop v4.0.5 (node v0.12.5)
├── strong-arc@1.4.4 (889bc42)
├── strong-build@2.0.2 (3221b91)
├── strong-deploy@2.2.2 (13baab4)
├── strong-pm@4.3.1 (45d254a)
├── strong-registry@1.1.5 (f46e58f)
├── strong-start@1.2.0 (e59f8b5)
├─┬ strong-supervisor@2.0.2 (610a578)
│ └── strong-agent@1.6.3
├── generator-loopback@1.10.1 (eae270c)
├── node-inspector@0.7.4
└── nodefly-register@0.3.3
```

**Comment by raymondfeng** [comment]
Check out the latest version, 

``` sh
cd loopback-example-ssl
rm -rf node_modules
npm i
node .
```

And it should work.
