### ISSUE TITLE
Update this example to StrongLoop 4

### ISSUE THREAD

**Issue by toXel** [strongloop/loopback-example-ssl#7]

**Comment by nqthqn** [comment]
**server.js** ?

``` js
var https = require('https');
var sslConfig = require('./ssl-config');

var options = {
  key: sslConfig.privateKey,
  cert: sslConfig.certificate
};

var app = module.exports = loopback();

app.start = function() {
  // start the web server
  return app.listen(app.get('port'), function() {
    var baseUrl = (httpOnly? 'http://' : 'https://') + app.get('host') + ':' + app.get('port');
    app.emit('started', baseUrl);
    console.log('LoopBack server listening @ %s%s', baseUrl, '/');
  });
};
```

**Comment by nqthqn** [comment]
```
TypeError: Cannot read property 'replace' of undefined
.-0     at EventEmitter.<anonymous> (/Users/nathann/code/vibi/server/boot/explorer.js:21:36)
.-0     at EventEmitter.g (events.js:261:16)
.-0     at emitOne (events.js:78:13)
.-0     at EventEmitter.emit (events.js:170:7)
.-0     at Server.<anonymous> (/Users/nathann/code/vibi/server/server.js:27:9)
.-0     at Server.g (events.js:261:16)
.-0     at emitNone (events.js:68:13)
.-0     at Server.emit (events.js:167:7)
.-0     at emitListeningNT (net.js:1264:10)
.-0     at nextTickCallbackWith1Arg (node.js:444:9)
```

**Comment by holisticode** [comment]
The above code doesn't work, the options are never used!

If I do it this way, 
https://localhost:3000/explorer won't appear in the browser, and only http works!
